-- Create Properties Table
create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  address text,
  city text,
  state text,
  zip text,
  price numeric,
  bedrooms numeric,
  bathrooms numeric,
  sqft numeric,
  lot_size numeric,
  year_built numeric,
  property_type text,
  hoa_fees numeric,
  days_on_market numeric,
  status text,
  description text,
  images text[],
  latitude numeric,
  longitude numeric,
  features text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.properties enable row level security;

-- Create Policy to allow public read access
create policy "Allow public read access"
  on public.properties for select
  using ( true );

-- Create Tours Table
create table public.tours (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id),
  name text,
  email text,
  phone text,
  message text,
  tour_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.tours enable row level security;

-- Create Policy to allow public insert (for now, or authenticated users only)
-- Since the requirement says "Login/Register should work", probably tours are for logged in users?
-- But the form might be public. Let's start with public insert for simplicity of testing.
create policy "Allow public insert to tours"
  on public.tours for insert
  with check ( true );
  
-- Allow reading own tours? Or admin?
create policy "Allow read access to tours"
  on public.tours for select
  using ( true );

