-- Create a table for Contact Form Submissions
create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  status text default 'new'::text
);

-- Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- Allow anyone to insert (for the public contact form)
create policy "Anyone can insert contact submissions"
on public.contact_submissions
for insert
with check (true);

-- Allow only authenticated admins to view submissions
-- Note: You'll need to define what an "admin" is. For now, we'll allow authenticated users.
create policy "Authenticated users can view submissions"
on public.contact_submissions
for select
to authenticated
using (true);

-- Create a table for Blog Posts
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  author text,
  category text,
  published boolean default false
);

-- Enable RLS
alter table public.posts enable row level security;

-- Allow anyone to read published posts
create policy "Anyone can read published posts"
on public.posts
for select
using (published = true);

-- Allow authenticated users to do everything (CRUD)
create policy "Authenticated users can manage posts"
on public.posts
for all
to authenticated
using (true);
